/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_clock.h"
#include "fsl_adc.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for GPIO peripheral */
#define GPIO_1_GPIO GPIO
/* Definition of peripheral ID */
#define USART_1_PERIPHERAL ((USART_Type *)FLEXCOMM4)
/* Definition of the clock source frequency */
#define USART_1_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_Flexcomm4)
/* Rx transfer buffer size. */
#define USART_1_TX_BUFFER_SIZE 4

/* Definitions for PERIPH_InitAdc functional group */
/* Alias for ADC0 peripheral */
#define ADC_1_PERIPHERAL ADC0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern gpio_pin_config_t GPIO_1_config[4];
extern const usart_config_t USART_1_config;
extern usart_handle_t USART_1_handle;
extern uint8_t USART_1_txBuffer[USART_1_TX_BUFFER_SIZE];
extern const usart_transfer_t USART_1_txTransfer;
extern const adc_config_t ADC_1configStruct;
extern const adc_conv_seq_config_t ADC_1ConvSeqAConfigStruct;
extern const adc_conv_seq_config_t ADC_1ConvSeqBConfigStruct;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* USART transfer callback function for the USART_1 component (init. function BOARD_InitPeripherals)*/
extern void USART_UserCallback(USART_Type *base, usart_handle_t *handle, status_t status, void *userData);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);
void PERIPH_InitAdc(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
