/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v1.0
processor: LPC54628J512
package_id: LPC54628J512ET180
mcu_data: ksdk2_0
processor_version: 3.0.1
board: LPCXpresso54628
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
  selectedCore: core0
- name: PERIPH_InitAdc
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * GPIO_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO_1'
- type: 'lpc_gpio'
- mode: 'GPIO'
- type_id: 'lpc_gpio_8c9ab9b3668a514c1f4609fe43001865'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO'
- config_sets:
  - lpc_gpio:
    - gpioConfig:
      - 0:
        - signal_number: 'PIO3.14'
        - pinDirection: 'kGPIO_DigitalOutput'
        - outputLogic: '1U'
      - 1:
        - signal_number: 'PIO3.3'
        - pinDirection: 'kGPIO_DigitalOutput'
        - outputLogic: '1U'
      - 2:
        - signal_number: 'PIO2.2'
        - pinDirection: 'kGPIO_DigitalOutput'
        - outputLogic: '0U'
      - 3:
        - signal_number: 'PIO3.24'
        - pinDirection: 'kGPIO_DigitalOutput'
        - outputLogic: '0U'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
gpio_pin_config_t GPIO_1_config[4] = {
  {
    .pinDirection = kGPIO_DigitalOutput,
    .outputLogic = 1U
  },
  {
    .pinDirection = kGPIO_DigitalOutput,
    .outputLogic = 1U
  },
  {
    .pinDirection = kGPIO_DigitalOutput,
    .outputLogic = 0U
  },
  {
    .pinDirection = kGPIO_DigitalOutput,
    .outputLogic = 0U
  }
};

void GPIO_1_init(void) {
  /* Initialize GPIO functionality on pin PIO3_14 */
  GPIO_PinInit(GPIO_1_GPIO, 3U, 14U, &GPIO_1_config[0]);
  /* Initialize GPIO functionality on pin PIO3_3 */
  GPIO_PinInit(GPIO_1_GPIO, 3U, 3U, &GPIO_1_config[1]);
  /* Initialize GPIO functionality on pin PIO2_2 */
  GPIO_PinInit(GPIO_1_GPIO, 2U, 2U, &GPIO_1_config[2]);
  /* Initialize GPIO functionality on pin PIO3_24 */
  GPIO_PinInit(GPIO_1_GPIO, 3U, 24U, &GPIO_1_config[3]);
}

/***********************************************************************************************************************
 * USART_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USART_1'
- type: 'flexcomm_usart'
- mode: 'transfer'
- type_id: 'flexcomm_usart_fcc110cc6b16332e9dfd9e0df675e21f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM4'
- config_sets:
  - transferCfg:
    - transfer:
      - init_rx_transfer: 'true'
      - rx_transfer:
        - data_size: '10'
      - init_tx_transfer: 'true'
      - tx_transfer:
        - data_size: '2'
      - init_callback: 'true'
      - callback_fcn: 'USART_UserCallback'
      - user_data: ''
  - usartConfig_t:
    - usartConfig:
      - baudRate_Bps: '115200'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableRx: 'true'
      - enableTx: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t USART_1_config = {
  .baudRate_Bps = 115200,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true
};
usart_handle_t USART_1_handle;
uint8_t USART_1_rxBuffer[USART_1_RX_BUFFER_SIZE];
const usart_transfer_t USART_1_rxTransfer = {
  .data = USART_1_rxBuffer,
  .dataSize = USART_1_RX_BUFFER_SIZE
};
uint8_t USART_1_txBuffer[USART_1_TX_BUFFER_SIZE];
const usart_transfer_t USART_1_txTransfer = {
  .data = USART_1_txBuffer,
  .dataSize = USART_1_TX_BUFFER_SIZE
};

void USART_1_init(void) {
  /* Reset FLEXCOMM device */
  RESET_PeripheralReset(kFC4_RST_SHIFT_RSTn);
  USART_Init(USART_1_PERIPHERAL, &USART_1_config, USART_1_CLOCK_SOURCE);
  USART_TransferCreateHandle(USART_1_PERIPHERAL, &USART_1_handle, USART_UserCallback, NULL);
}

/***********************************************************************************************************************
 * PERIPH_InitAdc functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * ADC_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC_1'
- type: 'lpc_adc'
- mode: 'ADC'
- type_id: 'lpc_adc_c8a42a3971e43028d68a2161b5fcb2b2'
- functional_group: 'PERIPH_InitAdc'
- peripheral: 'ADC0'
- config_sets:
  - fsl_adc:
    - enable_irq: 'false'
    - irq_src: 'kADC_ConvSeqAInterruptEnable'
    - adc_interrupt:
      - IRQn: 'ADC0_SEQA_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - doSelfCalibration: 'true'
    - enableTempSensor: 'false'
    - adcConfig:
      - clockMode: 'kADC_ClockSynchronousMode'
      - clockDividerNumber: '1'
      - resolution: 'kADC_Resolution12bit'
      - sampleTimeNumber: '0'
      - enableBypassCalibration: 'false'
    - thresholdConfig:
      - thresholdSettingsPair0:
        - ADC_SetThreshold: 'false'
      - thresholdSettingsPair1:
        - ADC_SetThreshold: 'false'
    - adcConvSeqConfigA:
      - enableSeqConfiguration: 'true'
      - enableHighPriority: 'false'
      - adcConvSeqConfig:
        - triggerMask: '0U'
        - triggerPolarity: 'kADC_TriggerPolarityNegativeEdge'
        - enableSyncBypass: 'false'
        - enableSingleStep: 'false'
        - interruptMode: 'kADC_InterruptForEachSequence'
    - adcConvSeqConfigB:
      - enableSeqConfiguration: 'true'
      - enableHighPriority: 'false'
      - adcConvSeqConfig:
        - triggerMask: '0U'
        - triggerPolarity: 'kADC_TriggerPolarityNegativeEdge'
        - enableSyncBypass: 'false'
        - enableSingleStep: 'false'
        - interruptMode: 'kADC_InterruptForEachSequence'
    - channels:
      - 0:
        - channelNumber: 'CH.4'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'a'
      - 1:
        - channelNumber: 'CH.5'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'a'
      - 2:
        - channelNumber: 'CH.6'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'b'
      - 3:
        - channelNumber: 'CH.7'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'b'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC_1configStruct = {
  .clockMode = kADC_ClockSynchronousMode,
  .clockDividerNumber = 1,
  .resolution = kADC_Resolution12bit,
  .sampleTimeNumber = 0,
  .enableBypassCalibration = false
};
/* Conversion sequence A configuration structure */
const adc_conv_seq_config_t ADC_1ConvSeqAConfigStruct = {
  .channelMask = 16U | 32U,
  .triggerMask = 0U,
  .triggerPolarity = kADC_TriggerPolarityNegativeEdge,
  .enableSyncBypass = false,
  .enableSingleStep = false,
  .interruptMode = kADC_InterruptForEachSequence
};
/* Conversion sequence B configuration structure */
const adc_conv_seq_config_t ADC_1ConvSeqBConfigStruct = {
  .channelMask = 64U | 128U,
  .triggerMask = 0U,
  .triggerPolarity = kADC_TriggerPolarityNegativeEdge,
  .enableSyncBypass = false,
  .enableSingleStep = false,
  .interruptMode = kADC_InterruptForEachSequence
};

void ADC_1_init(void) {
  /* Perform self calibration */
  ADC_DoSelfCalibration(ADC_1_PERIPHERAL);
  /* Initialize ADC0 peripheral */
  ADC_Init(ADC_1_PERIPHERAL, &ADC_1configStruct);
  /* Configure the conversion sequence A */
  ADC_SetConvSeqAConfig(ADC_1_PERIPHERAL, &ADC_1ConvSeqAConfigStruct);
  /* Enable the conversion sequence A */
  ADC_EnableConvSeqA(ADC_1_PERIPHERAL, true);
  /* Configure the conversion sequence B */
  ADC_SetConvSeqBConfig(ADC_1_PERIPHERAL, &ADC_1ConvSeqBConfigStruct);
  /* Enable the conversion sequence B */
  ADC_EnableConvSeqB(ADC_1_PERIPHERAL, true);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  GPIO_1_init();
  USART_1_init();
}

void PERIPH_InitAdc(void)
{
  /* Initialize components */
  ADC_1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
