/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v1.0
processor: LPC54628J512
package_id: LPC54628J512ET180
mcu_data: ksdk2_0
processor_version: 3.0.1
board: LPCXpresso54628
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * ADC_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC_1'
- type: 'lpc_adc'
- mode: 'ADC'
- type_id: 'lpc_adc_c8a42a3971e43028d68a2161b5fcb2b2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_adc:
    - enable_irq: 'true'
    - irq_src: 'kADC_ConvSeqAInterruptEnable'
    - adc_interrupt:
      - IRQn: 'ADC0_SEQA_IRQn'
      - enable_priority: 'true'
      - priority: '4'
      - enable_custom_name: 'false'
    - doSelfCalibration: 'true'
    - enableTempSensor: 'true'
    - adcConfig:
      - clockMode: 'kADC_ClockSynchronousMode'
      - clockDividerNumber: '1'
      - resolution: 'kADC_Resolution12bit'
      - sampleTimeNumber: '0'
      - enableBypassCalibration: 'false'
    - thresholdConfig:
      - thresholdSettingsPair0:
        - ADC_SetThreshold: 'false'
      - thresholdSettingsPair1:
        - ADC_SetThreshold: 'false'
    - adcConvSeqConfigA:
      - enableSeqConfiguration: 'true'
      - enableHighPriority: 'false'
      - adcConvSeqConfig:
        - triggerMask: '0U'
        - triggerPolarity: 'kADC_TriggerPolarityNegativeEdge'
        - enableSyncBypass: 'false'
        - enableSingleStep: 'false'
        - interruptMode: 'kADC_InterruptForEachSequence'
    - adcConvSeqConfigB:
      - enableSeqConfiguration: 'false'
    - channels:
      - 0:
        - channelNumber: 'CH.4'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'a'
      - 1:
        - channelNumber: 'CH.5'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'a'
      - 2:
        - channelNumber: 'CH.6'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'a'
      - 3:
        - channelNumber: 'CH.7'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'a'
      - 4:
        - channelNumber: 'CH.0'
        - channelThresholdPair: 'thresholdPair0'
        - thresholdInterruptMode: 'kADC_ThresholdInterruptDisabled'
        - conversion_sequence: 'a'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC_1configStruct = {
  .clockMode = kADC_ClockSynchronousMode,
  .clockDividerNumber = 1,
  .resolution = kADC_Resolution12bit,
  .sampleTimeNumber = 0,
  .enableBypassCalibration = false
};
/* Conversion sequence A configuration structure */
const adc_conv_seq_config_t ADC_1ConvSeqAConfigStruct = {
  .channelMask = 16U | 32U | 64U | 128U | 1U,
  .triggerMask = 0U,
  .triggerPolarity = kADC_TriggerPolarityNegativeEdge,
  .enableSyncBypass = false,
  .enableSingleStep = false,
  .interruptMode = kADC_InterruptForEachSequence
};

void ADC_1_init(void) {
  /* Perform self calibration */
  ADC_DoSelfCalibration(ADC_1_PERIPHERAL);
  /* Initialize ADC0 peripheral */
  ADC_Init(ADC_1_PERIPHERAL, &ADC_1configStruct);
  /* Enable temperature sensor on channel 0 */
  ADC_EnableTemperatureSensor(ADC_1_PERIPHERAL, true);
  /* Configure the conversion sequence A */
  ADC_SetConvSeqAConfig(ADC_1_PERIPHERAL, &ADC_1ConvSeqAConfigStruct);
  /* Enable the conversion sequence A */
  ADC_EnableConvSeqA(ADC_1_PERIPHERAL, true);
  /* Enable interrupt from ADC */
  ADC_EnableInterrupts(ADC_1_PERIPHERAL, kADC_ConvSeqAInterruptEnable);
  /* Enable interrupt in Nested Vectored Interrupt Controller */
  NVIC_EnableIRQ(ADC0_SEQA_IRQn);
  /* Configure threshold compare interrupt on channel 4 */
  ADC_EnableThresholdCompareInterrupt(ADC_1_PERIPHERAL, 4U, kADC_ThresholdInterruptDisabled);
  /* Configure threshold compare interrupt on channel 5 */
  ADC_EnableThresholdCompareInterrupt(ADC_1_PERIPHERAL, 5U, kADC_ThresholdInterruptDisabled);
  /* Configure threshold compare interrupt on channel 6 */
  ADC_EnableThresholdCompareInterrupt(ADC_1_PERIPHERAL, 6U, kADC_ThresholdInterruptDisabled);
  /* Configure threshold compare interrupt on channel 7 */
  ADC_EnableThresholdCompareInterrupt(ADC_1_PERIPHERAL, 7U, kADC_ThresholdInterruptDisabled);
  /* Configure threshold compare interrupt on channel 0 */
  ADC_EnableThresholdCompareInterrupt(ADC_1_PERIPHERAL, 0U, kADC_ThresholdInterruptDisabled);
  /* Interrupt vector ADC0_SEQA_IRQn priority settings in the NVIC */
  NVIC_SetPriority(ADC0_SEQA_IRQn, ADC_1_IRQ_PRIORITY);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  ADC_1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
