/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_adc.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for GPIO peripheral */
#define GPIO_1_GPIO GPIO

/* Definitions for PERIPH_InitAdc functional group */
/* Alias for ADC0 peripheral */
#define ADC_1_PERIPHERAL ADC0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern gpio_pin_config_t GPIO_1_config[3];
extern const adc_config_t ADC_1configStruct;
extern const adc_conv_seq_config_t ADC_1ConvSeqAConfigStruct;
extern const adc_conv_seq_config_t ADC_1ConvSeqBConfigStruct;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);
void PERIPH_InitAdc(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
